name: fastlane
on:
  push:
  
jobs:
  default:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
